Repository apache/incubator-kie-kogito-serverless-operator, pull requests merged in 2023-07, with the labels that each got.

#179 Differentiate descriptions of Address and Endpoint
  api/v1alpha08/sonataflow_types.go
  bundle/manifests/sonataflow.org_sonataflows.yaml
  config/crd/bases/sonataflow.org_sonataflows.yaml
  operator.yaml
Labels: backport-1.40.x

#183 [1.41.x] Allow to override the Container registry URL
  .ci/jenkins/Jenkinsfile.deploy
Labels: backport-main

#181 [KOGITO-9244] Platform.spec.platform.baseImage does not update the Dockerfile base image
  bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
  controllers/builder/containerbuilder.go
  controllers/builder/openshiftbuilder.go
  controllers/platform/platformutils.go
  controllers/platform/platformutils_test.go
  test/yaml.go
Labels: backport-1.40.x, backport-1.41.x

#196 KOGITO-9560 Use `latest` version in CSV
  Makefile
  bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  hack/bump-version.sh
  operator.yaml
Labels: backport-1.41.x

#202 Fix csv file on bump version
  bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
  config/manifests/bases/sonataflow-operator.clusterserviceversion.yaml
  hack/bump-version.sh
  hack/env.sh
Labels: backport-1.42.x
