Repository apache/incubator-kie-kogito-serverless-operator, pull requests merged in 2023-08, with the labels that each got.

#206 [KOGITO-9653] - Fix how to handle WaitingForDeployment condition to avoid pod duplication
  .gitignore
  controllers/profiles/reconciler_dev.go
  utils/kubernetes/deployment.go
Labels: bug, backport-1.40.x-prod, backport-1.42.x, backport-1.40.x, backport-1.41.x

#215 [KOGITO-8276] Fixing Dockerfile to COPY the new log package
  Dockerfile
  go.work.sum
Labels: backport-1.42.x

#216 [KOGITO-8276] Fix setup log
  bundle/manifests/sonataflow-operator.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  controllers/const.go
  docs/CONTRIBUTING.md
  main.go
  operator.yaml
Labels: backport-1.42.x

#229 [KOGITO-8794] - Making deployment handler profile independent
  controllers/platform/warm.go
  controllers/profiles/deployment.go
  controllers/profiles/object_creators.go
  controllers/profiles/reconciler_dev.go
  controllers/profiles/reconciler_prod.go
  controllers/profiles/reconciler_prod_test.go
  controllers/sonataflowplatform_controller.go
  utils/kubernetes/deployment.go
  utils/kubernetes/deployment_failure.go
  workflowproj/operator.go
Labels: backport-1.43.x
